version: '2.4'

services:
  docker:
    image: docker:latest
    privileged: true   # Required to run Docker inside a container
    ports:
      - "2375:2375"    # Exposing Docker API (optional, use with caution)
    environment:
      DOCKER_TLS_CERTDIR: ""  # Disable TLS for local development

  app-generator:
    container_name: app-generator
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"  # Map the host port to the container port
      - "8501:8501"  # Map the host port to the container port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Access Docker Engine from the container
      - .:/usr/app
    environment:
      - DOCKER_HOST=http://127.0.0.1:2376 # Connect to the Docker Engine (modify as necessary)
