FROM nginx:latest

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/

# Copy the static HTML files into the Nginx html directory
COPY ./html /usr/share/nginx/html

# Expose port 5000 to allow external access
EXPOSE 5000

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]
