import os
import re
import markdown
from weasyprint import HTML


def extract_code(text : str, file_type : str) -> str:
    """
    Extracts the source code of a specified file type from LLM-generated text.

    This function looks for code enclosed between triple backticks (```) with an optional
    language identifier (e.g., `python`, `javascript`). It first attempts to extract code
    enclosed with the given file type, and if it fails, it tries to extract any enclosed code.

    @param text: The input text generated by the LLM that potentially contains code.
    @param file_type: The expected type of code to extract (e.g., 'python', 'javascript').

    @return: The extracted code block from the text.

    @raise ValueError: If no code block is found in the provided text.
    """
    match = re.search(r'```' + file_type + r'(.*)```', text, re.DOTALL)
    if match == None:
        match = re.search(r'```(.*)```', text, re.DOTALL)
    if match == None:
        raise ValueError(f'No source code found in the provided text.')
    return match.group(1)


def extract_imports_from_file(file_path):
    """
    Extracts all imports from a given Python file.

    This function reads the provided Python file line by line and uses regular expressions
    to find import statements. It filters out standard library imports and certain
    predefined internal modules.

    @param file_path: Path to the Python file from which imports are to be extracted.

    @return: A set of unique package names imported in the file.
    """
    imports = set()
    with open(file_path, 'r', encoding="utf8") as file:
        for line in file:
            # Match regular import statements: import x or from x import y
            match = re.match(r'^\s*(import|from)\s+([\w\.]+)', line)
            if match:
                package_name = match.group(2).split('.')[0]
                if package_name not in ['backend', 'mqtt_lib', 'server', "flask", "paho"]:
                    imports.add(package_name)
    return imports


def extract_imports_from_directory(directory):
    """
    Extracts all imports from Python files in the specified directory.

    This function recursively traverses the directory, identifies Python files,
    and aggregates the imports found in each file.

    @param directory: The directory path to search for Python files.

    @return: A set of unique imports from all Python files within the directory.
    """
    all_imports = set()
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith('.py'):
                file_path = os.path.join(root, file)
                all_imports.update(extract_imports_from_file(file_path))
    return all_imports

def extract_pdf_from_markdown(input_text: str, output_path: str) -> None:
    # Convert Markdown to HTML
    html_content = markdown.markdown(input_text, extensions=['fenced_code', 'tables'])

    # Customized CSS with smaller margins and enhanced styling
    html = f"""
    <html>
        <head>
            <meta charset="utf-8">
            <style>
                @page {{
                    size: A4;
                    margin: 0.5in; /* Reduced margin */
                }}
                body {{
                    font-family: Arial, sans-serif;
                    margin: 0; /* Use @page margin */
                    font-size: 12pt;
                    line-height: 1.2;
                }}
                h1, h2, h3, h4, h5, h6 {{
                    margin-top: 1em;
                    margin-bottom: 0.5em;
                }}
                p {{
                    margin-bottom: 1em;
                }}
                pre {{
                    background-color: #f4f4f4;
                    padding: 10px;
                    border: 1px solid #ddd;
                    overflow-x: auto;
                    white-space: pre-wrap; /* Allow wrapping */
                    word-wrap: break-word; /* Break long words */
                }}
                code {{
                    background-color: #f4f4f4;
                    padding: 2px 4px;
                    border-radius: 4px;
                }}
                table {{
                    border-collapse: collapse;
                    width: 100%; /* Full width tables */
                    margin-bottom: 1em;
                }}
                th, td {{
                    border: 1px solid #ddd;
                    padding: 8px;
                    text-align: left;
                    word-wrap: break-word;
                }}
                th {{
                    background-color: #f2f2f2;
                }}
                ul, ol {{
                    margin-bottom: 1em;
                    padding-left: 40px; /* Indent lists */
                }}
                li {{
                    margin-bottom: 0.5em; /* Space between list items */
                    display: list-item; /* Ensure list items are block-level */
                    /* Optional: Adjust list item markers */
                    /* list-style-type: disc; for ul */
                    /* list-style-type: decimal; for ol */
                }}
                blockquote {{
                    border-left: 4px solid #ddd;
                    padding-left: 10px;
                    color: #555;
                    margin-left: 0;
                    margin-right: 0;
                    margin-bottom: 1em;
                }}
                /* Ensure that list items do not display inline */
                ul li, ol li {{
                    display: list-item;
                }}
                /* Optional: Prevent lists from being wrapped incorrectly */
                ul, ol {{
                    display: block;
                }}
            </style>
        </head>
        <body>
            {html_content}
        </body>
    </html>
    """

    HTML(string=html).write_pdf(output_path)
    
